import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import Link from 'next/link'



export default function Home() {
        
  const [index,setIndex] = useState(0)
  const images = ["/image1.jpg","/image2.jpg","/image3.jpg","/image4.jpg","/image5.jpg","/image6.jpg"]
  const HandleClick =(direction)=>{
    if(direction==="left"){
     setIndex(index!==0?index-1:5)
    }else if(direction==="right"){
     setIndex(index!==5?index+1:0)
    }
   }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div onClick={()=>HandleClick('left')} className={styles.Arrow} style={{left:5}}>
        <Image width={50} height={50} src='/arrowl.png' alt=''/>
      </div>
    
        <div className={styles.Left}>
          <div className={styles.Wrapper} style={{transform:`translateX(${-50*index}vw)`}}>
            
            {images.map((im,i)=>(
             <div key={i} style={{position:"relative",width:"50vw",height:"80vh"}}> 
               <Image  src={im} alt='' layout='fill' objectFit="cover"/>
             </div> 
            ))}

          </div>
        </div>
        <div className={styles.Right}>
        <div onClick={()=>HandleClick('right')} className={styles.Arrow} style={{left:"-80px"}}>
        <Image width={50} height={50} src='/arrowr.png' alt=''/>
      </div>
        <h1 className={styles.Title}>UrbanMobile</h1>
        <p style={{fontSize:"19px",wordSpacing:'5px',padding:"0 10px"}}>Si vous souhaitez voyager en tant que chauffeur, tout ce que vous avez à faire est de choisir la destination spécifique avec la date à laquelle vous souhaitez voyager et de créer le voyage, pius vous attendez  que les passagers voient votre offre et y réservent des places 
          
            UrbanMobile c est la première application de covoiturage en algerie, fondée par deux érudiants amar ould hamadouche et chawki naouar en 2022
        </p>
        <Link href={'https://expo.dev/artifacts/36e97da1-a2b4-4bea-acd5-3dab424e64f1'} passHref>
          <div className={styles.Button}>Télecharger</div>
        </Link>
          
       
      </div>
       
    </div>
  )
}
